### ISSUE TITLE
Thinks button is always pressed?

### ISSUE THREAD

**Issue by opjose** [hoopsurfer/pdx#2]
I want to run this script on a PI equipped with the 735 ver 2.1 and an 825 in the Geekworm metal case.
When I install the package and reboot, the system shuts down after a few seconds.
When I pull the MicroSD card I can see in the logs that the PI thinks the button is being pressed.
I see the messages from the powerkey.py script in the logs indicating a 5 second press.

However if I run the original Geekworm script for the 735 this does not happen.

Any idea as to what I can change to fix this?

Thanks for writing this btw!

**Comment by hoopsurfer** [comment]
I need more details, can you provide output of pdx-check?  Does short power button press cause reboot?  Long press case shutdown?

**Comment by opjose** [comment]
I cannot let the powerkey service script run as it shuts down my Pi before it finishes booting, so the button presses do not trigger the script.

Here is the output of the pdx-check command and what the daemon.log showed when it was enabled.

Other than the Geekworm hardware I do not have anything connected to the GPIO pins.

Thanks!

[pdx-check-logfile.txt](https://github.com/hoopsurfer/pdx/files/4668172/pdx-check-logfile.txt)
[daemon.log](https://github.com/hoopsurfer/pdx/files/4668173/daemon.log)

**Comment by opjose** [comment]
Well this turned out to be a non-issue.

I commented out the reboot and shutdown lines and set the gpio messages to TRUE so I could see what was going on.  I ran the powerkeys script manually and immediately saw a message about something else using the same pins... and of course it was right.

There was a routine installed on the Picade distro I am running that monitors pins for a different multiswitch device.

That was the problem all along!

Thank you for replying.

You can close this out.

THANKS!!!!
